2021-03-05 00:03:17,513, DEBUG, Запуск Telegram-бота, homework
2021-03-05 00:03:17,727, DEBUG, Entering: send_message, telegram.bot
2021-03-05 00:03:17,727, DEBUG, Starting new HTTPS connection (1): api.telegram.org, telegram.vendor.ptb_urllib3.urllib3.connectionpool
2021-03-05 00:03:17,969, DEBUG, https://api.telegram.org:443 "POST /bot1699728423:AAFejC7pC-A3caQaSmOzQopSpQUsVEFEOhE/sendMessage HTTP/1.1" 200 585, telegram.vendor.ptb_urllib3.urllib3.connectionpool
2021-03-05 00:03:17,969, DEBUG, {'message_id': 88, 'date': 1614891798, 'chat': {'id': 263225424, 'type': 'private', 'username': 'blackbaccy', 'first_name': 'Tim'}, 'text': 'У вас проверили работу "bdcry__api_sp1_bot.zip"!\n\nК сожалению в работе нашлись ошибки.', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1699728423, 'first_name': 'PraktikumBot', 'is_bot': True, 'username': 'PraktikumDontCryBot'}}, telegram.bot
2021-03-05 00:03:17,969, DEBUG, Exiting: send_message, telegram.bot
2021-03-05 00:09:02,108, DEBUG, Запуск Telegram-бота, homework
2021-03-05 00:09:02,320, DEBUG, Entering: send_message, telegram.bot
2021-03-05 00:09:02,320, DEBUG, Starting new HTTPS connection (1): api.telegram.org, telegram.vendor.ptb_urllib3.urllib3.connectionpool
2021-03-05 00:09:02,556, DEBUG, https://api.telegram.org:443 "POST /bot1699728423:AAFejC7pC-A3caQaSmOzQopSpQUsVEFEOhE/sendMessage HTTP/1.1" 200 585, telegram.vendor.ptb_urllib3.urllib3.connectionpool
2021-03-05 00:09:02,556, DEBUG, {'message_id': 89, 'date': 1614892143, 'chat': {'id': 263225424, 'type': 'private', 'username': 'blackbaccy', 'first_name': 'Tim'}, 'text': 'У вас проверили работу "bdcry__api_sp1_bot.zip"!\n\nК сожалению в работе нашлись ошибки.', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1699728423, 'first_name': 'PraktikumBot', 'is_bot': True, 'username': 'PraktikumDontCryBot'}}, telegram.bot
2021-03-05 00:09:02,556, DEBUG, Exiting: send_message, telegram.bot
2021-03-05 00:11:14,448, DEBUG, Запуск Telegram-бота, homework
2021-03-05 00:11:14,791, DEBUG, Entering: send_message, telegram.bot
2021-03-05 00:11:14,791, DEBUG, Starting new HTTPS connection (1): api.telegram.org, telegram.vendor.ptb_urllib3.urllib3.connectionpool
2021-03-05 00:11:15,011, DEBUG, https://api.telegram.org:443 "POST /bot1699728423:AAFejC7pC-A3caQaSmOzQopSpQUsVEFEOhE/sendMessage HTTP/1.1" 200 585, telegram.vendor.ptb_urllib3.urllib3.connectionpool
2021-03-05 00:11:15,011, DEBUG, {'message_id': 90, 'date': 1614892275, 'chat': {'id': 263225424, 'type': 'private', 'username': 'blackbaccy', 'first_name': 'Tim'}, 'text': 'У вас проверили работу "bdcry__api_sp1_bot.zip"!\n\nК сожалению в работе нашлись ошибки.', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 1699728423, 'first_name': 'PraktikumBot', 'is_bot': True, 'username': 'PraktikumDontCryBot'}}, telegram.bot
2021-03-05 00:11:15,011, DEBUG, Exiting: send_message, telegram.bot
